### ISSUE TITLE
Configure Dependabot in `.github/dependabot.yml`

### ISSUE THREAD

**Issue by lszrn** [railnova/kafka-example#5]
Something like:

```yaml
version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 0
```
